services:
    db:
        image: postgres:15
        container_name: postgres_container
        ports:
            - '${DB_PORT}:5432'
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app_network

volumes:
    postgres_data:
        driver: local

networks:
    app_network: