services:
    db:
        image: postgres:15
        container_name: database
        ports:
            - '5434:5434'
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf
        command: postgres -c config_file=/etc/postgresql/postgresql.conf
        networks:
            - app_network
        restart: "always"

    aider-thierry-api:
        container_name : backend
        build: 
            context: .
            dockerfile: backend/dockerfile
        ports:
            - "5432:3000"
        networks:
            - app_network
        restart: "always"
        depends_on:
            - db

    frontend:
        container_name: frontend
        build:
            context: ./web-app
            dockerfile: dockerfile
        ports:
            - "5433:8080"
        networks:
            - app_network
        depends_on:
            - aider-thierry-api


volumes:
    postgres_data:
        driver: local

networks:
    app_network: