name: Build APK with Expo

on:
  push:
    branches:
      - '**'

jobs:
  build-apk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Log in to Expo
        run: eas whoami || eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Build APK
        run: eas build --platform android --non-interactive --profile preview

      - name: Upload build URL
        run: echo "APK URL:" && eas build:list --platform android --limit 1 --json | jq -r '.[0].artifacts.buildUrl'
